---
- name: ngrok directory
  file:
    path: "{{ ngrok_dir }}/{{ item }}"
    state: directory
    mode: 0655
    owner: root
    group: wheel
    recurse: yes
  with_items:
  - bin
  - etc
  - log
- name: Check for ngrok
  stat: "path={{ ngrok_dir }}/bin/ngrok"
  register: ngrok
- name: Get ngrok
  get_url:
    dest: "{{ ngrok_dir }}/"
    url: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
  when: ngrok.stat.exists == False
- name: Unpack ngrok
  unarchive:
    src: "{{ ngrok_dir }}/ngrok-stable-linux-amd64.zip"
    dest: "{{ ngrok_dir }}/bin/"
    copy: no
  when: ngrok.stat.exists == False
- name: Kill ngrok if running
  command: killall ngrok
  ignore_errors: yes
- name: ngrok configuration file
  template:
    src: ngrok.yml.j2
    dest: "{{ ngrok_dir }}/etc/ngrok.yml"
- name: ngrok tls tunnels running
  shell: "nohup {{ ngrok_dir }}/bin/ngrok start {{ item }}-{{ ngrok_tunnel_proto }} --config {{ ngrok_dir }}/etc/ngrok.yml &"
  with_items: "{{ sites }}"
